version: "2.0"

triggering:
  cancel_previous_builds: true

workflows:
  build:
    name: Build App
    environment:
      vars:
        FLUTTER_VERSION: "latest"
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - flutter pub get
      # - flutter build ios --release
      - flutter build apk --release
    artifacts:
      # - build/**/outputs/**/*.ipa
      - build/**/outputs/**/*.apk

publishing:
  slack:
    channel: "#cicd"
    notify_on_build_start: true
    notify:
      success: true
      failure: true
