name: Build and Publish
on:
  - workflow_call
  - workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        run: |
          curl -X POST ${{ secrets.CODEMAGIC_WEBHOOK }} \
               -H "Content-Type: application/json" \
               -d '{}'
