name: Build and Publish
on:
  workflow_call:
    inputs:
      branch:
        description: "Branch to build"
        type: string
        required: true
        default: "main"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        type: string
        required: true
        default: "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic build
        run: |
          curl -X POST https://api.codemagic.io/builds \
          -H 'Content-Type: application/json' \
          -H 'X-Auth-Token: ${{ secrets.CODEMAGIC_API_TOKEN }}' \
          -d '{
                "appId": "${{ secrets.CODEMAGIC_APP_ID }}",
                "workflowId": "build",
                "branch": "${{ inputs.branch }}"
              }'
