name: CD for Branch env with Label
on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    if: >-
      ${{
        github.event.label.name == 'PR Deploy'
      }}
    steps:
      - uses: actions/checkout@v3
  ci:
    uses: ./.github/workflows/ci.yml
    needs:
      - prepare
    secrets: inherit
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    needs:
      - ci
      - prepare
    with:
      branch: ${{ github.head_ref }}
      workflowId: branch-build
    secrets: inherit
