name: CD for Main
on:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  #  ci:
  #    uses: ./.github/workflows/ci.yml
  #    secrets: inherit
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    secrets: inherit
