name: CD for Main
on:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Get current branch
        id: branch
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    needs:
      - prepare
      - ci
    with:
      branch: ${{ needs.prepare.outputs.branch }}
    secrets: inherit
