name: CI
on:
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.8"
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.8"
          channel: "stable"

      - name: flutter pub get
        run: flutter pub get

      - name: dart format lib
        run: dart format lib --set-exit-if-changed

      - name: dart analyze
        run: dart analyze
