name: CI
on:
  - workflow_call
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: flutter cache
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.10.0"
        channel: "stable"
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter

      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: "stable"

      - name: flutter pub get
        run: flutter pub get

      - name: flutter format lib
        run: flutter format lib

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test
